<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriesSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('PRAGMA foreign_keys = OFF;');
        DB::table('categories')->truncate();

        $data = array (
  0 => 
  array (
    'id' => 1,
    'code' => 'cm01',
    'name' => 'オリエンテーション',
    'parent_id' => NULL,
    'top_id' => 1,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2026/1/11 20:50',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => 'システム管理者',
  ),
  1 => 
  array (
    'id' => 2,
    'code' => 'cm02',
    'name' => '各種手引き',
    'parent_id' => NULL,
    'top_id' => 2,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  2 => 
  array (
    'id' => 3,
    'code' => 'cm03',
    'name' => '就職支援',
    'parent_id' => NULL,
    'top_id' => 3,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  3 => 
  array (
    'id' => 4,
    'code' => 'cm04',
    'name' => 'ビジネスマナー',
    'parent_id' => NULL,
    'top_id' => 4,
    'level' => 1,
    'child_count' => 2,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  4 => 
  array (
    'id' => 5,
    'code' => 'cm04-1',
    'name' => '職業人講話',
    'parent_id' => 4,
    'top_id' => 4,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  5 => 
  array (
    'id' => 6,
    'code' => 'cm04-2',
    'name' => '電話対応スキル',
    'parent_id' => 4,
    'top_id' => 4,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  6 => 
  array (
    'id' => 7,
    'code' => 'cm05',
    'name' => 'IT基礎',
    'parent_id' => NULL,
    'top_id' => 7,
    'level' => 1,
    'child_count' => 5,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  7 => 
  array (
    'id' => 8,
    'code' => 'cm05-01',
    'name' => 'パソコン基礎演習',
    'parent_id' => 7,
    'top_id' => 7,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  8 => 
  array (
    'id' => 9,
    'code' => 'cm05-02',
    'name' => 'コンピュータ概論',
    'parent_id' => 7,
    'top_id' => 7,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  9 => 
  array (
    'id' => 10,
    'code' => 'cm05-03',
    'name' => 'ネットワーク概論',
    'parent_id' => 7,
    'top_id' => 7,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  10 => 
  array (
    'id' => 11,
    'code' => 'cm05-04',
    'name' => 'プログラミング概論',
    'parent_id' => 7,
    'top_id' => 7,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  11 => 
  array (
    'id' => 12,
    'code' => 'cm05-05',
    'name' => '情報技術概論（ITパスポート）',
    'parent_id' => 7,
    'top_id' => 7,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  12 => 
  array (
    'id' => 13,
    'code' => 'cm06',
    'name' => 'Webデザイン関連',
    'parent_id' => NULL,
    'top_id' => 13,
    'level' => 1,
    'child_count' => 4,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  13 => 
  array (
    'id' => 14,
    'code' => 'cm06-01',
    'name' => 'デザイン基礎',
    'parent_id' => 13,
    'top_id' => 13,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  14 => 
  array (
    'id' => 15,
    'code' => 'cm06-02',
    'name' => 'Illustrator&Photoshop基礎',
    'parent_id' => 13,
    'top_id' => 13,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  15 => 
  array (
    'id' => 16,
    'code' => 'cm06-03',
    'name' => 'Illustrator&Photoshop演習',
    'parent_id' => 13,
    'top_id' => 13,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  16 => 
  array (
    'id' => 17,
    'code' => 'cm06-04',
    'name' => 'Webデザイン演習',
    'parent_id' => 13,
    'top_id' => 13,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  17 => 
  array (
    'id' => 18,
    'code' => 'cm07',
    'name' => 'Javaプログラミング',
    'parent_id' => NULL,
    'top_id' => 18,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  18 => 
  array (
    'id' => 19,
    'code' => 'cm08',
    'name' => 'HTML＆CSSプログラミング',
    'parent_id' => NULL,
    'top_id' => 19,
    'level' => 1,
    'child_count' => 2,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  19 => 
  array (
    'id' => 20,
    'code' => 'cm08-01',
    'name' => 'HTML＆CSS基本',
    'parent_id' => 19,
    'top_id' => 19,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  20 => 
  array (
    'id' => 21,
    'code' => 'cm08-02',
    'name' => 'HTML＆CSS演習',
    'parent_id' => 19,
    'top_id' => 19,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  21 => 
  array (
    'id' => 22,
    'code' => 'cm09',
    'name' => 'JavaScriptプログラミング',
    'parent_id' => NULL,
    'top_id' => 22,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  22 => 
  array (
    'id' => 23,
    'code' => 'cm10',
    'name' => 'Webサイト制作演習（ポートフォリオ作成）',
    'parent_id' => NULL,
    'top_id' => 23,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  23 => 
  array (
    'id' => 24,
    'code' => 'cm11',
    'name' => 'データベース基本演習',
    'parent_id' => NULL,
    'top_id' => 24,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  24 => 
  array (
    'id' => 25,
    'code' => 'cm12',
    'name' => 'PHPプログラミング演習',
    'parent_id' => NULL,
    'top_id' => 25,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  25 => 
  array (
    'id' => 26,
    'code' => 'cm13',
    'name' => 'CMSによるWebサイトの構築演習（WordPress）',
    'parent_id' => NULL,
    'top_id' => 26,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  26 => 
  array (
    'id' => 27,
    'code' => 'cm14',
    'name' => 'LaravelによるWebアプリ作成',
    'parent_id' => NULL,
    'top_id' => 27,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  27 => 
  array (
    'id' => 28,
    'code' => 'cm15',
    'name' => 'Web制作実習関連',
    'parent_id' => NULL,
    'top_id' => 28,
    'level' => 1,
    'child_count' => 4,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  28 => 
  array (
    'id' => 33,
    'code' => 'cm16',
    'name' => '制作プレゼンテーション',
    'parent_id' => NULL,
    'top_id' => 33,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  29 => 
  array (
    'id' => 34,
    'code' => 'cm17',
    'name' => 'ダウンロード',
    'parent_id' => NULL,
    'top_id' => 34,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/26 20:28',
    'updated_at' => '2025/11/26 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  30 => 
  array (
    'id' => 35,
    'code' => 'cm21',
    'name' => 'テレワーク実務科',
    'parent_id' => NULL,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 16,
    'is_show' => 1,
    'created_at' => '2025/11/27 20:28',
    'updated_at' => '2025/11/27 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  31 => 
  array (
    'id' => 36,
    'code' => 'cm21-01',
    'name' => 'ビジネスマナー',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/28 20:28',
    'updated_at' => '2025/11/28 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  32 => 
  array (
    'id' => 37,
    'code' => 'cm21-04',
    'name' => 'Eメールとメーラー',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/29 20:28',
    'updated_at' => '2025/11/29 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  33 => 
  array (
    'id' => 38,
    'code' => 'cm21-06',
    'name' => 'コミュニケーションソフト',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/11/30 20:28',
    'updated_at' => '2025/11/30 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  34 => 
  array (
    'id' => 39,
    'code' => 'cm21-07',
    'name' => 'パソコンの各種設定とセキュリティ管理',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/1 20:28',
    'updated_at' => '2025/12/1 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  35 => 
  array (
    'id' => 40,
    'code' => 'cm21-16',
    'name' => '配色&カラーデザイン概論',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/2 20:28',
    'updated_at' => '2025/12/2 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  36 => 
  array (
    'id' => 41,
    'code' => 'cm21-17',
    'name' => 'デザインソフトの活用',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/3 20:28',
    'updated_at' => '2025/12/3 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  37 => 
  array (
    'id' => 42,
    'code' => 'cm21-18',
    'name' => 'ホームページ作成演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/4 20:28',
    'updated_at' => '2025/12/4 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  38 => 
  array (
    'id' => 43,
    'code' => 'cm21-19',
    'name' => '文書作成演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/5 20:28',
    'updated_at' => '2025/12/5 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  39 => 
  array (
    'id' => 44,
    'code' => 'cm21-20',
    'name' => '表計算ソフト演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/6 20:28',
    'updated_at' => '2025/12/6 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  40 => 
  array (
    'id' => 45,
    'code' => 'cm21-22',
    'name' => 'プレゼンテーションソフト演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/7 20:28',
    'updated_at' => '2025/12/7 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  41 => 
  array (
    'id' => 46,
    'code' => 'cm21-23',
    'name' => 'ビジネス文書作成演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/8 20:28',
    'updated_at' => '2025/12/8 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  42 => 
  array (
    'id' => 47,
    'code' => 'cm21-24',
    'name' => '表計算ソフト応用演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/9 20:28',
    'updated_at' => '2025/12/9 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  43 => 
  array (
    'id' => 48,
    'code' => 'cm21-25',
    'name' => 'Excelスペシャリスト試験の演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/10 20:28',
    'updated_at' => '2025/12/10 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  44 => 
  array (
    'id' => 49,
    'code' => 'cm21-26',
    'name' => '表計算ソフト応用マクロ・VBA演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/11 20:28',
    'updated_at' => '2025/12/11 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  45 => 
  array (
    'id' => 50,
    'code' => 'cm21-27',
    'name' => 'データベースソフト演習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/12 20:28',
    'updated_at' => '2025/12/12 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  46 => 
  array (
    'id' => 51,
    'code' => 'cm21-28',
    'name' => 'OAアプリの制作実習',
    'parent_id' => 35,
    'top_id' => 35,
    'level' => 1,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/13 20:28',
    'updated_at' => '2025/12/13 20:28',
    'deleted_at' => NULL,
    'created_user_name' => 'システム管理者',
    'updated_user_name' => 'システム管理者',
    'deleted_user_name' => NULL,
  ),
  47 => 
  array (
    'id' => 52,
    'code' => 'cm18',
    'name' => '求人用ダウンロード',
    'parent_id' => 34,
    'top_id' => 34,
    'level' => 2,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/3 13:55',
    'updated_at' => '2025/12/3 13:56',
    'deleted_at' => NULL,
    'created_user_name' => NULL,
    'updated_user_name' => NULL,
    'deleted_user_name' => NULL,
  ),
  48 => 
  array (
    'id' => 53,
    'code' => 'cm19',
    'name' => '各種届出ダウンロード',
    'parent_id' => 34,
    'top_id' => 34,
    'level' => 2,
    'child_count' => 0,
    'is_show' => 1,
    'created_at' => '2025/12/3 13:57',
    'updated_at' => '2025/12/3 13:57',
    'deleted_at' => NULL,
    'created_user_name' => NULL,
    'updated_user_name' => NULL,
    'deleted_user_name' => NULL,
  ),
);

        DB::table('categories')->insert($data);

        DB::statement('PRAGMA foreign_keys = ON;');
    }
}