<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategoriesSeeder extends Seeder
{
    public function run(): void
    {
        // 外部キー制約を一時的に OFF
        if (DB::getDriverName() === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = OFF;');
        } else {
            DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        }

        // 既存データをクリア
        DB::table('categories')->truncate();

        $categories = [
            // 親カテゴリ（parent_id = 0）
            [
                'id' => 1,
                'code' => 'cm01',
                'name' => 'オリエンテーション',
                'parent_id' => NULL,
                'top_id' => 1,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 2,
                'code' => 'cm02',
                'name' => '各種手引き',
                'parent_id' => NULL,
                'top_id' => 2,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 3,
                'code' => 'cm03',
                'name' => '就職支援',
                'parent_id' => NULL,
                'top_id' => 3,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 4,
                'code' => 'cm04',
                'name' => 'ビジネスマナー',
                'parent_id' => NULL,
                'top_id' => 4,
                'level' => 1,
                'child_count' => 2,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 7,
                'code' => 'cm05',
                'name' => 'IT基礎',
                'parent_id' => NULL,
                'top_id' => 7,
                'level' => 1,
                'child_count' => 5,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 13,
                'code' => 'cm06',
                'name' => 'Webデザイン関連',
                'parent_id' => NULL,
                'top_id' => 13,
                'level' => 1,
                'child_count' => 4,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 18,
                'code' => 'cm07',
                'name' => 'Javaプログラミング',
                'parent_id' => NULL,
                'top_id' => 18,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 19,
                'code' => 'cm08',
                'name' => 'HTML＆CSSプログラミング',
                'parent_id' => NULL,
                'top_id' => 19,
                'level' => 1,
                'child_count' => 2,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 22,
                'code' => 'cm09',
                'name' => 'JavaScriptプログラミング',
                'parent_id' => NULL,
                'top_id' => 22,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 23,
                'code' => 'cm10',
                'name' => 'Webサイト制作演習（ポートフォリオ作成）',
                'parent_id' => NULL,
                'top_id' => 23,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 24,
                'code' => 'cm11',
                'name' => 'データベース基本演習',
                'parent_id' => NULL,
                'top_id' => 24,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 25,
                'code' => 'cm12',
                'name' => 'PHPプログラミング演習',
                'parent_id' => NULL,
                'top_id' => 25,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 26,
                'code' => 'cm13',
                'name' => 'CMSによるWebサイトの構築演習（WordPress）',
                'parent_id' => NULL,
                'top_id' => 26,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 27,
                'code' => 'cm14',
                'name' => 'LaravelによるWebアプリ作成',
                'parent_id' => NULL,
                'top_id' => 27,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 28,
                'code' => 'cm15',
                'name' => 'Web制作実習関連',
                'parent_id' => NULL,
                'top_id' => 28,
                'level' => 1,
                'child_count' => 4,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 33,
                'code' => 'cm16',
                'name' => '制作プレゼンテーション',
                'parent_id' => NULL,
                'top_id' => 33,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 34,
                'code' => 'cm17',
                'name' => 'ダウンロード',
                'parent_id' => NULL,
                'top_id' => 34,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            // 子カテゴリ（parent_id ≠ 0）
            [
                'id' => 5,
                'code' => 'cm04-1',
                'name' => '職業人講話',
                'parent_id' => 4,
                'top_id' => 4,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 6,
                'code' => 'cm04-2',
                'name' => '電話対応スキル',
                'parent_id' => 4,
                'top_id' => 4,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 8,
                'code' => 'cm05-01',
                'name' => 'パソコン基礎演習',
                'parent_id' => 7,
                'top_id' => 7,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 9,
                'code' => 'cm05-02',
                'name' => 'コンピュータ概論',
                'parent_id' => 7,
                'top_id' => 7,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 10,
                'code' => 'cm05-03',
                'name' => 'ネットワーク概論',
                'parent_id' => 7,
                'top_id' => 7,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 11,
                'code' => 'cm05-04',
                'name' => 'プログラミング概論',
                'parent_id' => 7,
                'top_id' => 7,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 12,
                'code' => 'cm05-05',
                'name' => '情報技術概論（ITパスポート）',
                'parent_id' => 7,
                'top_id' => 7,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 14,
                'code' => 'cm06-01',
                'name' => 'デザイン基礎',
                'parent_id' => 13,
                'top_id' => 13,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 15,
                'code' => 'cm06-02',
                'name' => 'Illustrator&Photoshop基礎',
                'parent_id' => 13,
                'top_id' => 13,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 16,
                'code' => 'cm06-03',
                'name' => 'Illustrator&Photoshop演習',
                'parent_id' => 13,
                'top_id' => 13,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 17,
                'code' => 'cm06-04',
                'name' => 'Webデザイン演習',
                'parent_id' => 13,
                'top_id' => 13,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 20,
                'code' => 'cm08-01',
                'name' => 'HTML＆CSS基本',
                'parent_id' => 19,
                'top_id' => 19,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 21,
                'code' => 'cm08-02',
                'name' => 'HTML＆CSS演習',
                'parent_id' => 19,
                'top_id' => 19,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],

            [
                'id' => 35,
                'code' => 'cm17-01',
                'name' => '求人用',
                'parent_id' => 34,
                'top_id' => 34,
                'level' => 1,
                'child_count' => 0,
                'is_show' => true,
                'created_at' => now(),
                'created_user_name' => 'システム管理者',
                'updated_at' => now(),
                'updated_user_name' => 'システム管理者',
            ],
            // ... 必要に応じて残りの子カテゴリも追加
        ];

        DB::table('categories')->insert($categories);

        // 外部キー制約を再有効化
        if (DB::getDriverName() === 'sqlite') {
            DB::statement('PRAGMA foreign_keys = ON;');
        } else {
            DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        }
    }
}
